/**
 * Copy what the map draws into public/, at build time.
 *
 * Two files, from two places, and neither is copied into git. The court map is generated by
 * `scripts/locate_instante.py` in this simulator; the county outlines come from the
 * administrative simulator, which already exports them and is the only place they should be
 * maintained. Copying at build time rather than committing a second copy is what stops the
 * two drifting — a duplicated boundary file is a boundary file that will one day disagree
 * with itself.
 */
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../public/data');
mkdirSync(out, { recursive: true });

const ADMIN = (name) => resolve(here, `../../../administrativ/web/public/data/${name}`);

const sources = [
  // The latest edition. Older ones stay in data/ so the two years can be compared.
  [resolve(here, '../../data/instante-localizate-2025.json'), 'instante.json'],
  [
    resolve(here, '../../../administrativ/web/public/data/counties.geojson'),
    'counties.geojson',
  ],
  // The proposal is a document with its own provenance, not a constant in the code: what the
  // page claims the reform says has to be checkable against the paper it was read from.
  [resolve(here, '../../data/propunere-harta-judiciara.json'), 'propunere.json'],
  // The chapters that argue rather than measure, quoted with their pages.
  [resolve(here, '../../data/design-reforma.json'), 'design.json'],
  // Pay grades and the wage bill, so the staffing control can price what it moves.
  [resolve(here, '../../data/costuri-2025.json'), 'costuri.json'],
  // The two pension reforms, so the page can show them against each other.
  [resolve(here, '../../data/pensii-comparatie.json'), 'pensii.json'],
  // What the courts pay above base salary, and what it does to the bill's headline.
  [resolve(here, '../../data/sporuri-2025.json'), 'sporuri.json'],
  // The same judges priced under the July 2026 pay draft.
  [resolve(here, '../../data/costuri-proiect-2026.json'), 'proiect.json'],
  // Consolidated UATs assigned to courts by distance, county lines ignored.
  [resolve(here, '../../data/arondare-noua.json'), 'arondare-noua.json'],
  [resolve(here, '../../data/court-distance.json'), 'court-distance.json'],
  // Hospitals, as the only county-scale service with a public national register.
  [resolve(here, '../../data/spitale-2026.json'), 'spitale.json'],
  [resolve(here, '../../data/acces-servicii.json'), 'servicii.json'],
  [resolve(here, '../../data/politie-osm.json'), 'politie.json'],
  // The paper's efficiency premise, against the report it cites for it.
  [resolve(here, '../../data/eficienta-csm.json'), 'eficienta.json'],
  // The prosecution service, reorganised in parallel by 7.3.
  [resolve(here, '../../data/parchete-2025.json'), 'parchete.json'],
  // What each of the 42 proposed courts would have to judge, routed through the new map.
  [resolve(here, '../../data/incarcatura-noua.json'), 'incarcatura.json'],
  // What 7.3's merger does to prosecution workload, on the CSM's published volumes.
  [resolve(here, '../../data/parchete-comasare.json'), 'parchete-comasare.json'],
  // A variant, not the paper: the appellate prosecution tier grouped on the same eight regions.
  [resolve(here, '../../data/parchete-regiuni.json'), 'parchete-regiuni.json'],
  // How far the prosecution establishment sits from its own caseload.
  [resolve(here, '../../data/parchete-incadrare.json'), 'parchete-incadrare.json'],
  // Prosecution routed by distance with the courts, not merged by county.
  [resolve(here, '../../data/parchete-arondare.json'), 'parchete-arondare.json'],
  // Chapters 4-5: the Danish comparison the paper's judicial map rests on.
  [resolve(here, '../../data/danemarca-comparatie.json'), 'danemarca.json'],
  // Chapter 16's resource figures, against the pay grid and estate they have to agree with.
  [resolve(here, '../../data/resurse-necesare.json'), 'resurse.json'],
  // The paper itself, so a reader can learn what the reform is before what does not hold.
  [resolve(here, '../../data/lucrarea.json'), 'lucrarea.json'],
  // The ledger: which chapters this page checks, quotes, or leaves alone.
  [resolve(here, '../../data/acoperire.json'), 'acoperire.json'],
  // A variant, not the paper: eight appellate courts instead of the fifteen it proposes.
  [resolve(here, '../../data/curti-apel-regiuni.json'), 'curti-apel.json'],
  [resolve(here, '../../data/court-distance.bin'), 'court-distance.bin'],
  // The administrative model's own payload, so the merge can be re-run here as the reader
  // moves the sliders. Copied rather than fetched across from the administrative site: 1,6 MB
  // is the price of this page working when it is the only one deployed.
  [ADMIN('manifest.json'), 'admin-manifest.json'],
  [ADMIN('attributes.json'), 'admin-attributes.json'],
  [ADMIN('attributes.bin'), 'admin-attributes.bin'],
  [ADMIN('adjacency.bin'), 'admin-adjacency.bin'],
  [ADMIN('candidacy.bin'), 'admin-candidacy.bin'],
  // The road network the distances are measured on, for the map to show on request.

  // What the case files say, aggregated: workload, termene, duration, charges. Built by
  // scripts/build_portal_stats.py from the daily portal snapshots.
  [resolve(here, '../../data/portal-stats.json'), 'portal-stats.json'],
  // The same measurements per court, and only in forms that add up — counts and histograms,
  // never a percentile. It is what lets the statistics page answer for a county, an appeal
  // circumscription or one of the proposed courts rather than only for the country.
  [resolve(here, '../../data/portal-instante.json'), 'portal-instante.json'],
  // Cases filed per court, which no published source states.
  [resolve(here, '../../data/intrate-portal.json'), 'intrate-portal.json'],
  // Four consecutive CSM editions. The portal cannot show how the system changed — its old
  // years are a survival sample — so the trend has to come from a source that counted every
  // case at the time.
  [resolve(here, '../../data/instante-2022.json'), 'instante-2022.json'],
  [resolve(here, '../../data/instante-2023.json'), 'instante-2023.json'],
  [resolve(here, '../../data/instante-2024.json'), 'instante-2024.json'],
  [resolve(here, '../../data/instante-2025.json'), 'instante-2025.json'],
  // County codes to full names, so a merged court is "Tribunalul Covasna" and not "CV".
  [resolve(here, '../../../administrativ/web/public/data/manifest.json'), 'manifest.json'],
];

// The road geometry is OPTIONAL. It is 2,4 MB of derived map context fetched from release
// data-v1 rather than committed — see data-assets.json — so a checkout that has not run
// scripts/fetch_release_data.py legitimately lacks it. Treating it like the required payloads
// failed the build outright, which is a worse outcome than a map missing one context layer.
const roads = ADMIN('roads.geojson');
if (existsSync(roads)) {
  copyFileSync(roads, resolve(out, 'roads.geojson'));
  console.log('copied roads.geojson');
} else {
  console.log('roads.geojson absent — the roads toggle will disable itself');
}

// The portal payloads are OPTIONAL, for the same reason roads.geojson is: they are rebuilt from
// a crawl that takes hours and are not committed while they hold a placeholder sample. A
// checkout without them legitimately lacks them, and the statistics page says so on its own
// rather than the whole build failing and taking the map down with it.
const optional = new Set(['portal-stats.json', 'portal-instante.json', 'intrate-portal.json']);

for (const [from, name] of sources) {
  if (!existsSync(from) && optional.has(name)) {
    console.log(`${name} absent — the statistics page will say so`);
    continue;
  }
  if (!existsSync(from)) {
    console.error(
      `missing ${from}\n` +
        'Run `uv run python simulators/justitie/scripts/locate_instante.py` from the ' +
        'repository root, and make sure the administrative payload is exported.',
    );
    process.exit(1);
  }
  copyFileSync(from, resolve(out, name));
  console.log(`copied ${name}`);
}
