/**
 * Copy what the map draws into public/, at build time.
 *
 * Two files, from two places, and neither is copied into git. The court map is generated by
 * `scripts/locate_instante.py` in this simulator; the county outlines come from the
 * administrative simulator, which already exports them and is the only place they should be
 * maintained. Copying at build time rather than committing a second copy is what stops the
 * two drifting — a duplicated boundary file is a boundary file that will one day disagree
 * with itself.
 */
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../public/data');
mkdirSync(out, { recursive: true });

const sources = [
  // The latest edition. Older ones stay in data/ so the two years can be compared.
  [resolve(here, '../../data/instante-localizate-2025.json'), 'instante.json'],
  [
    resolve(here, '../../../administrativ/web/public/data/counties.geojson'),
    'counties.geojson',
  ],
];

for (const [from, name] of sources) {
  if (!existsSync(from)) {
    console.error(
      `missing ${from}\n` +
        'Run `uv run python simulators/justitie/scripts/locate_instante.py` from the ' +
        'repository root, and make sure the administrative payload is exported.',
    );
    process.exit(1);
  }
  copyFileSync(from, resolve(out, name));
  console.log(`copied ${name}`);
}
